In [78]:
import numpy as np
import pandas as pd

In [79]:
df = pd.read_csv("~/Downloads/Splitwise expenses Jan 23.csv")

In [80]:
df.head(20)

,Date,Description,Category,Cost,Currency,James Lavis,Annika
0,2025-07-03,Amazon Waterbottle,General,19.00,EUR,-19.00,19.00
1,2025-07-03,Laundry,Services,5.00,EUR,2.50,-2.50
2,2025-07-03,Nail scisssors,General,5.95,EUR,-5.95,5.95
3,2025-07-03,Groceries,Groceries,19.00,EUR,9.50,-9.50
4,2025-07-03,Grocery’s,Groceries,16.97,EUR,8.48,-8.48
5,2025-07-04,Aldi,Groceries,7.65,EUR,-3.82,3.82
6,2025-07-08,Amazon,General,20.38,EUR,-20.38,20.38
7,2025-07-11,Mensa,Dining out,3.50,EUR,-3.50,3.50
8,2025-07-11,Bakery,General,7.00,EUR,-3.50,3.50
9,2025-07-11,Mensa,Dining out,2.80,EUR,-2.80,2.80
10,2025-07-12,Aldi shop,Groceries,57.33,EUR,28.67,-28.67
11,2025-07-17,Aldi,Groceries,9.69,EUR,4.85,-4.85
12,2025-07-17,Dish soap,Household supplies,1.95,EUR,0.97,-0.97
13,2025-07-19,Udon,Dining out,14.50,EUR,-14.50,14.50
14,2025-07-22,Aldi shop,Groceries,34.45,EUR,17.22,-17.22
15,2025-07-23,Mensa,Dining out,2.79,EUR,-2.79,2.79
16,2025-07-23,Cake,Gifts,4.00,EUR,-4.00,4.00
17,2025-07-23,Anni Cash Out,General,280.00,EUR,-280.00,280.00
18,2025-07-25,Foood,General,13.80,EUR,-13.80,13.80
19,2025-07-26,McDonald’s,Dining out,13.00,EUR,-13.00,13.00

In [81]:
df = df[df["Cost"] != " "]

df.index = pd.to_datetime(df["Date"])
df["Cost"] = df["Cost"].astype(float)

In [82]:
df["Month"] = df.index.month
df["Year"] = df.index.year

df.loc[df["Category"] == "Taxi", "Category"] = "Dining out"
df.loc[df["Category"] == "Household supplies", "Category"] = "Dining out"
df.loc[df["Description"].str.lower().str.contains("dm"), "Category"] = "Groceries"
df.loc[df["Description"] == "Vacuum ", "Category"] = "General" 

df.loc[df["Description"].isin(
    [
        "Frittenwerk",
        "Maccas",
        "Maccas ",
        "Asian food"
    ]
), "Category"] = "Dining out"

df.loc[df["Description"].isin(
    [
        "Presents Mama&Papa",
        "Wine for Neils"
    ]
), "Category"] = "Gifts"

df.loc[df["Description"].isin(["Thrift store"]), "Category"] = "Misc"

misc_categories = [
    'TV/Phone/Internet',
    'Movies', 
    'Bus/train', 
    'Sports', 
    'Liquor',
]

df.loc[df["Description"].isin(misc_categories), "Category"] = "Misc"

In [83]:
df["Category"].unique()

array(['General', 'Services', 'Groceries', 'Dining out', 'Gifts',
       'Payment', 'Gas/fuel', 'Parking', 'Transportation - Other',
       'Furniture', 'TV/Phone/Internet', 'Movies', 'Bus/train', 'Sports',
       'Misc'], dtype=object)

In [84]:
# df[df["Category"] == "General"]

In [85]:
df.groupby(["Month"])["Cost"].sum()

Month
1      494.07
7      902.56
8      577.31
9      498.52
10     547.49
11    1318.97
12     332.86
Name: Cost, dtype: float64

In [86]:
df_agg = df.groupby(["Month", "Category"])["Cost"].agg(["sum"]).reset_index()

In [87]:
df_agg[df_agg["Category"]=="Groceries"]

    Month   Category     sum
3       1  Groceries  297.57
8       7  Groceries  169.89
15      8  Groceries  105.20
23      9  Groceries  188.83
29     10  Groceries  118.50
35     11  Groceries  285.48
42     12  Groceries   51.24

In [88]:
df_agg[df_agg["Category"]=="Dining out"]

    Month    Category     sum
0       1  Dining out   90.50
5       7  Dining out   38.54
11      8  Dining out   70.09
20      9  Dining out   64.90
26     10  Dining out   48.87
31     11  Dining out  257.33
38     12  Dining out   69.66

In [89]:
df[np.logical_and(df["Category"] == "Dining out", df["Month"]==1)]

,Date,Description,Category,Cost,Currency,James Lavis,Annika,Month,Year
Date,,,,,,,,,
2026-01-02,2026-01-02,Maccas,Dining out,21.00,EUR,-9.99,9.99,1,2026
2026-01-03,2026-01-03,Asian food,Dining out,12.50,EUR,-12.50,12.50,1,2026
2026-01-14,2026-01-14,Thalia coffee and cake,Dining out,13.20,EUR,-6.60,6.60,1,2026
2026-01-14,2026-01-14,McDonalds,Dining out,20.78,EUR,-10.39,10.39,1,2026
2026-01-18,2026-01-18,Indian,Dining out,23.02,EUR,11.51,-11.51,1,2026

In [90]:
df_agg["Category"].unique()

array(['Dining out', 'Furniture', 'General', 'Groceries', 'Misc', 'Gifts',
       'Payment', 'Services', 'Gas/fuel', 'Movies', 'Parking',
       'TV/Phone/Internet', 'Transportation - Other', 'Bus/train',
       'Sports'], dtype=object)

In [91]:
df[df["Description"].str.lower().str.contains("maccas")]["Description"].unique()

array(['Maccas', 'Maccas '], dtype=object)

In [94]:
df[np.logical_and(df["Month"] == 1, df["Annika"] > 0)]["Annika"].sum()

np.float64(107.35000000000001)

In [95]:
df[df["Month"] == 1]

,Date,Description,Category,Cost,Currency,James Lavis,Annika,Month,Year
Date,,,,,,,,,
2026-01-02,2026-01-02,Maccas,Dining out,21.00,EUR,-9.99,9.99,1,2026
2026-01-03,2026-01-03,Asian food,Dining out,12.50,EUR,-12.50,12.50,1,2026
2026-01-05,2026-01-05,Hamburg,General,31.00,EUR,15.50,-15.50,1,2026
2026-01-08,2026-01-08,Aldi,Groceries,67.05,EUR,33.52,-33.52,1,2026
2026-01-10,2026-01-10,Aldi,Groceries,20.49,EUR,10.24,-10.24,1,2026
2026-01-12,2026-01-12,Aldi,Groceries,17.28,EUR,8.64,-8.64,1,2026
2026-01-14,2026-01-14,Thalia coffee and cake,Dining out,13.20,EUR,-6.60,6.60,1,2026
2026-01-14,2026-01-14,McDonalds,Dining out,20.78,EUR,-10.39,10.39,1,2026
2026-01-14,2026-01-14,Dm and rewe,Groceries,15.97,EUR,-7.98,7.98,1,2026
2026-01-14,2026-01-14,Lebara,General,7.18,EUR,-7.18,7.18,1,2026
2026-01-15,2026-01-15,Aldi & Dm,Groceries,38.02,EUR,-19.01,19.01,1,2026
2026-01-16,2026-01-16,Aldi,Groceries,29.54,EUR,14.77,-14.77,1,2026
2026-01-17,2026-01-17,Thrift store,Misc,10.50,EUR,-5.25,5.25,1,2026
2026-01-17,2026-01-17,Ikea,Furniture,24.00,EUR,-12.00,12.00,1,2026
2026-01-18,2026-01-18,Sunday,General,33.32,EUR,16.66,-16.66,1,2026
2026-01-18,2026-01-18,Indian,Dining out,23.02,EUR,11.51,-11.51,1,2026
2026-01-22,2026-01-22,Dm,Groceries,32.90,EUR,-16.45,16.45,1,2026
2026-01-22,2026-01-22,Aldi,Groceries,76.32,EUR,38.16,-38.16,1,2026

In [ ]:
df[""]